language: node_js
node_js:
  - 10

branches:
  only:
    - master

cache: npm

install:
  - npm ci

script:
  - npm run build

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/zRunner/**/*
    skip_cleanup: true
    on:
      tags: true

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: dist/showcase
    on:
      branch: master
