language: node_js
node_js:
  - 10

branches:
  only:
    - master

cache: npm

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/showcase
  on:
    branch: master
